<?php

/**
 * Implements hook_theme().
 */
function drupalcamp_theme() {
  $theme['register_page'] = [
    'variables' => [
      'content' => NULL,
      'registerForm' => NULL,
    ],
  ];
  $theme['proposal_page'] = [
    'variables' => [
      'content' => NULL,
      'proposalForm' => NULL,
    ],
  ];
  $theme['location_page'] = [
      'variables' => [
          'content' => NULL,
      ],
  ];

  return $theme;
}

